
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20140611 (SVN rev 31)
// Tue May 23 08:11:30 BRT 2017
//----------------------------------------------------

package compiler;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DIVIDE = 6;
  public static final int INTEGER_LIT = 37;
  public static final int LT_PAREN = 9;
  public static final int INTEGER = 29;
  public static final int SEMI = 7;
  public static final int LESS = 13;
  public static final int MINUS = 5;
  public static final int AND = 35;
  public static final int NOT = 21;
  public static final int INF = 2;
  public static final int OR = 20;
  public static final int COMMA = 8;
  public static final int BEGIN = 32;
  public static final int PLUS = 4;
  public static final int IF = 26;
  public static final int DOT = 19;
  public static final int EOF = 0;
  public static final int BOOLEAN = 31;
  public static final int GTR = 12;
  public static final int error = 1;
  public static final int PROGRAM = 34;
  public static final int RT_PAREN = 10;
  public static final int EQ = 11;
  public static final int ASSMNT = 18;
  public static final int REAL = 30;
  public static final int TIMES = 3;
  public static final int COLON = 17;
  public static final int BOOLEAN_LIT = 39;
  public static final int ELSE = 25;
  public static final int NOT_EQ = 16;
  public static final int WHILE = 23;
  public static final int LESS_EQ = 14;
  public static final int REAL_LIT = 38;
  public static final int THEN = 24;
  public static final int END = 27;
  public static final int GTR_EQ = 15;
  public static final int VAR = 33;
  public static final int PROCEDURE = 28;
  public static final int DO = 22;
  public static final int IDENTIFIER = 36;
}

